### ISSUE TITLE
Arreglar estilos para que se vean bien las card en las secciones del acerca de Andino.

### ISSUE THREAD

**Issue by abenassi** [datosgobar/datosgobar-acerca#3]
Se agregó una nueva sección en progreso para el Acerca de datos.gob.ar, con indicadores de monitoreo de la red de datos abiertos, pero los estilos de las tarjetas no están funcionando.

La sección se modifica en el archivo `monitoreo.md`, para ver los cambios debe ejecutarse `make build` y ver el "preview" de cómo se vería esa nueva sección del acerca en Andino, en la carpeta `docs/monitoreo.html`.

Hay que investigar y corregir el uso de las librerías / estilos en monitoreo.md para que funcione bien en Andino, o decidir si Andino debe modificar algo para tolerar mejor los estilos.

**Comment by pepeciavirella** [comment]
Corregir los estilos de las `Card`s para que no se vean en itálica:

<img width="1351" alt="Screenshot 2019-10-16 15 14 23" src="https://user-images.githubusercontent.com/28818765/66949683-50204f00-f02d-11e9-8c90-a5279c3e533a.png">

**Comment by pepeciavirella** [comment]
Corregir los estilos de las `Card`s para que no se vean en itálica:

<img width="1351" alt="Screenshot 2019-10-16 15 14 23" src="https://user-images.githubusercontent.com/28818765/66949683-50204f00-f02d-11e9-8c90-a5279c3e533a.png">
